#!/usr/bin/env Rscript
countries <- c("GBR", "NZL")
pkgload::load_all()

dest <- file.path(cometr_file(), "extdata")
unlink(dest, recursive = TRUE)
dir.create(dest, FALSE, TRUE)
for (name in countries) {
  message(sprintf("Updating '%s'", name))
  update_country_data(name, dest)
}
